"use client";

import { useMemo, useState } from "react";

type ClaimStatus = "Draft" | "Approved" | "Submitted" | "Credit Received" | "Matched";
type Program = { id:number; supplier:string; name:string; upc:string; start:string; end:string; rate:number; minimumUnits:number; confidence:number; source:string };
type Claim = { id:string; program:string; supplier:string; units:number; eligibleSales:number; expected:number; credit:number; reference:string; status:ClaimStatus };
type AuditEvent = { time:string; actor:string; action:string; entity:string };

const seedProgram: Program = { id:1, supplier:"Synthetic Foods Co.", name:"Summer Display Allowance", upc:"012345678905", start:"2026-07-01", end:"2026-07-31", rate:0.25, minimumUnits:100, confidence:94, source:"Program: Summer Display Allowance. UPC 012345678905. Valid 2026-07-01 through 2026-07-31. Earn $0.25 per unit after 100 units." };
const initialClaims: Claim[] = [{ id:"CLM-1001", program:"Summer Display Allowance", supplier:"Synthetic Foods Co.", units:200, eligibleSales:900, expected:50, credit:0, reference:"", status:"Draft" }];
const nextStatus: Partial<Record<ClaimStatus,ClaimStatus>> = { Draft:"Approved", Approved:"Submitted", Submitted:"Credit Received", "Credit Received":"Matched" };
const tone: Record<ClaimStatus,string> = { Draft:"bg-slate-700 text-slate-100", Approved:"border-blue-500/30 bg-blue-500/15 text-blue-300", Submitted:"border-amber-500/30 bg-amber-500/15 text-amber-300", "Credit Received":"border-violet-500/30 bg-violet-500/15 text-violet-300", Matched:"border-emerald-500/30 bg-emerald-500/15 text-emerald-300" };
const usd=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);

export default function AllowanceOSAI(){
 const [tab,setTab]=useState("Dashboard");
 const [programs,setPrograms]=useState<Program[]>([seedProgram]);
 const [claims,setClaims]=useState<Claim[]>(initialClaims);
 const [selectedId,setSelectedId]=useState("CLM-1001");
 const [agreement,setAgreement]=useState(seedProgram.source);
 const [draft,setDraft]=useState<Program|null>(null);
 const [credit,setCredit]=useState("50.00");
 const [reference,setReference]=useState("CM-DEMO-001");
 const [notice,setNotice]=useState("Interactive operational-system demonstration loaded with synthetic records.");
 const [audit,setAudit]=useState<AuditEvent[]>([
  {time:"22:28:15",actor:"Engine",action:"Eligible funding calculated",entity:"CLM-1001"},
  {time:"22:28:12",actor:"Owner",action:"Program reviewed and activated",entity:"Program #1"},
  {time:"22:28:10",actor:"System",action:"Synthetic demonstration initialized",entity:"Organization"}
 ]);
 const selected=claims.find(c=>c.id===selectedId)??claims[0];
 const totals=useMemo(()=>({expected:claims.reduce((s,c)=>s+c.expected,0),recovered:claims.filter(c=>c.status==="Matched").reduce((s,c)=>s+c.credit,0),open:claims.filter(c=>c.status!=="Matched").reduce((s,c)=>s+Math.max(c.expected-c.credit,0),0)}),[claims]);
 const log=(action:string,entity:string)=>setAudit(items=>[{time:new Date().toLocaleTimeString([],{hour12:false}),actor:"Owner",action,entity},...items]);
 const extract=()=>{ const upc=agreement.match(/\b\d{12,14}\b/)?.[0]??"Review required"; const dates=agreement.match(/20\d{2}-\d{2}-\d{2}/g)??[]; const rate=Number(agreement.match(/\$\s*(\d+(?:\.\d+)?)/)?.[1]??0); const minimum=Number(agreement.match(/(?:after|minimum|over)\s*(\d+)\s*units/i)?.[1]??0); const complete=[upc!=="Review required",dates.length>=2,rate>0,minimum>0].filter(Boolean).length; setDraft({id:programs.length+1,supplier:"Synthetic Foods Co.",name:agreement.match(/Program:\s*([^\.]+)/i)?.[1]?.trim()??"Extracted supplier program",upc,start:dates[0]??"Review required",end:dates[1]??"Review required",rate,minimumUnits:minimum,confidence:complete*25,source:agreement}); setNotice("AI-assisted extraction completed. Human validation is required before activation."); log("Agreement terms extracted for review","Program draft"); };
 const activate=()=>{if(!draft)return;setPrograms(p=>[draft,...p]);log("Program reviewed and activated",`Program #${draft.id}`);setNotice("Program validated by a human reviewer and activated.");setDraft(null)};
 const calculate=(p:Program)=>{const units=240,eligibleSales=1080,expected=units>=p.minimumUnits?units*p.rate:0,id=`CLM-${1001+claims.length}`;setClaims(c=>[{id,program:p.name,supplier:p.supplier,units,eligibleSales,expected,credit:0,reference:"",status:"Draft"},...c]);setSelectedId(id);setTab("Claims");setNotice(`${id} calculated from synthetic sales activity and opened for review.`);log("Eligible funding calculated",id)};
 const advance=()=>{if(!selected||selected.status==="Matched")return;const next=nextStatus[selected.status];if(!next)return;setClaims(items=>items.map(c=>c.id!==selected.id?c:next==="Credit Received"?{...c,status:next,credit:Number(credit||0),reference}:{...c,status:next}));setNotice(`${selected.id} advanced to ${next}. Audit event recorded.`);log(next==="Matched"?"Accounting match verified":`Claim advanced to ${next}`,selected.id)};
 return <div className="min-h-screen rounded-3xl bg-[#06101d] text-slate-100 shadow-2xl shadow-black/30">
  <header className="border-b border-slate-800"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-5 lg:flex-row lg:items-center"><div className="mr-auto flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-400 font-black text-slate-950">A</div><div><h1 className="text-lg font-semibold">AllowanceOS AI</h1><p className="text-xs text-slate-500">Employee-enabled supplier-funding recovery</p></div></div><nav className="flex max-w-full gap-2 overflow-x-auto">{["Dashboard","Programs","Claims","Audit","Subscription"].map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium ${tab===x?"bg-teal-400 text-slate-950":"text-slate-400 hover:bg-slate-900 hover:text-white"}`}>{x}</button>)}</nav></div></header>
  <main className="mx-auto max-w-7xl px-5 py-8"><div className="mb-6 rounded-xl border border-teal-400/20 bg-teal-400/5 px-4 py-3 text-sm text-teal-100">{notice}</div>
  {tab==="Dashboard"&&<><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Kpi label="Expected funding" value={usd(totals.expected)} note="Calculated from active programs"/><Kpi label="Verified recovery" value={usd(totals.recovered)} note="Only matched credits qualify"/><Kpi label="Open balance" value={usd(totals.open)} note="Financial value still unresolved"/><Kpi label="Active programs" value={String(programs.length)} note="Human-reviewed supplier terms"/></section><section className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Panel title="Recovery ledger"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-3">Claim</th><th>Program</th><th>Expected</th><th>Received</th><th>Status</th></tr></thead><tbody>{claims.map(c=><tr key={c.id} className="border-t border-slate-800"><td className="py-4 font-medium">{c.id}</td><td>{c.program}</td><td>{usd(c.expected)}</td><td>{usd(c.credit)}</td><td><Status value={c.status}/></td></tr>)}</tbody></table></div></Panel><Panel title="Employee authority remains central"><p className="text-sm leading-6 text-slate-400">AI organizes terms and calculations. Supermarket personnel validate programs, authorize claims, document supplier responses, and verify financial recovery.</p><ol className="mt-5 space-y-3 text-sm text-slate-300"><li>1. AI extracts and calculates</li><li>2. Employees review and approve</li><li>3. Finance verifies credits</li><li>4. Audit history preserves accountability</li></ol></Panel></section></>}
  {tab==="Programs"&&<section className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Panel title="AI-assisted agreement intake"><p className="text-sm text-slate-500">Paste supplier terms. Extraction creates a review draft and never activates a program automatically.</p><textarea value={agreement} onChange={e=>setAgreement(e.target.value)} rows={10} className="mt-5 w-full rounded-xl border border-slate-700 bg-slate-950 p-4 text-sm leading-6 outline-none focus:border-teal-400"/><button onClick={extract} className="mt-4 w-full rounded-xl bg-teal-400 px-4 py-3 font-semibold text-slate-950">Extract review draft</button></Panel><div>{draft&&<div className="mb-5 rounded-2xl border border-amber-400/30 bg-amber-400/5 p-5"><div className="flex justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-amber-300">Human review required</p><h3 className="mt-2 text-xl font-semibold">{draft.name}</h3></div><span className="h-fit rounded-full border border-amber-400/30 px-3 py-1 text-xs text-amber-300">{draft.confidence}% confidence</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="UPC" value={draft.upc}/><Field label="Period" value={`${draft.start} to ${draft.end}`}/><Field label="Rate" value={`${usd(draft.rate)} per unit`}/><Field label="Minimum" value={`${draft.minimumUnits} units`}/></div><button onClick={activate} className="mt-5 rounded-xl bg-amber-300 px-4 py-2.5 font-semibold text-slate-950">Validate and activate</button></div>}<Panel title="Active programs"><div className="space-y-3">{programs.map(p=><div key={p.id} className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{p.name}</p><p className="mt-1 text-sm text-slate-500">{p.supplier} · UPC {p.upc}</p></div><span className="h-fit rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">Active</span></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm"><span className="text-slate-400">{usd(p.rate)}/unit after {p.minimumUnits} units</span><button onClick={()=>calculate(p)} className="rounded-lg border border-teal-400/30 bg-teal-400/10 px-3 py-2 font-semibold text-teal-300">Calculate claim</button></div></div>)}</div></Panel></div></section>}
  {tab==="Claims"&&<section className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><Panel title="Claims queue"><div className="space-y-2">{claims.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full rounded-xl border p-4 text-left ${selected.id===c.id?"border-teal-400 bg-teal-400/5":"border-slate-800 bg-slate-950/60"}`}><div className="flex items-center justify-between"><span className="font-semibold">{c.id}</span><Status value={c.status}/></div><p className="mt-2 text-sm text-slate-400">{c.program}</p><p className="mt-3 text-xl font-semibold">{usd(c.expected)}</p></button>)}</div></Panel><Panel title={`Controlled case ${selected.id}`}><div className="grid gap-4 sm:grid-cols-2"><Field label="Eligible units" value={selected.units.toLocaleString()}/><Field label="Eligible sales" value={usd(selected.eligibleSales)}/><Field label="Expected funding" value={usd(selected.expected)}/><Field label="Credit received" value={usd(selected.credit)}/></div>{selected.status==="Submitted"&&<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-400">Credit amount<input value={credit} onChange={e=>setCredit(e.target.value)} type="number" className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white"/></label><label className="text-sm text-slate-400">Credit reference<input value={reference} onChange={e=>setReference(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white"/></label></div>}<div className="mt-5 flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950/70 p-4"><span className="text-sm text-slate-400">Current state</span><Status value={selected.status}/></div>{selected.status!=="Matched"&&<button onClick={advance} className="mt-5 w-full rounded-xl bg-teal-400 px-4 py-3 font-semibold text-slate-950">{selected.status==="Draft"?"Approve claim":selected.status==="Approved"?"Mark submitted":selected.status==="Submitted"?"Record credit":"Verify accounting match"}</button>}</Panel></section>}
  {tab==="Audit"&&<Panel title="Tamper-evident audit history"><p className="mb-5 text-sm text-slate-500">This browser demonstration visualizes the linked audit model used by the operational pilot.</p><div className="space-y-3">{audit.map((a,i)=><div key={`${a.time}-${i}`} className="grid gap-2 rounded-xl border border-slate-800 bg-slate-950/60 p-4 md:grid-cols-[110px_120px_1fr_150px]"><span className="font-mono text-xs text-teal-300">{a.time}</span><span className="text-sm text-slate-400">{a.actor}</span><span className="text-sm">{a.action}</span><span className="text-sm text-slate-500">{a.entity}</span></div>)}</div></Panel>}
  {tab==="Subscription"&&<><div className="max-w-2xl"><p className="text-xs uppercase tracking-[.18em] text-teal-300">Recurring-revenue architecture</p><h2 className="mt-3 text-3xl font-semibold">Price against verified customer value.</h2><p className="mt-3 leading-7 text-slate-400">Monthly plans combine access, workflow volume, and measurable recovered value. Live payment collection belongs in the secured operational layer.</p></div><div className="mt-8 grid gap-5 md:grid-cols-3"><Plan name="Pilot" price="$299" detail="1 store · 100 monthly claims"/><Plan name="Growth" price="$799" detail="Up to 5 stores · 500 claims" featured/><Plan name="Regional" price="Contract" detail="Multi-store integrations and controls"/></div></>}
  <footer className="mt-10 border-t border-slate-800 pt-6 text-xs leading-5 text-slate-600">Interactive demonstration using synthetic records. It preserves the operational product concept without representing browser data as production supermarket activity.</footer></main></div>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</div>}
function Field({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 font-semibold">{value}</p></div>}
function Status({value}:{value:ClaimStatus}){return <span className={`rounded-full border border-transparent px-2.5 py-1 text-xs ${tone[value]}`}>{value}</span>}
function Kpi({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded-2xl border border-slate-800 bg-gradient-to-br from-teal-400/15 to-transparent p-5"><p className="text-xs uppercase tracking-[.18em] text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></div>}
function Plan({name,price,detail,featured=false}:{name:string;price:string;detail:string;featured?:boolean}){return <div className={`rounded-2xl border ${featured?"border-teal-400/50":"border-slate-700"} bg-slate-900/70 p-6`}><p className="text-sm text-slate-400">{name}</p><p className="mt-4 text-4xl font-semibold">{price}</p><p className="mt-2 text-sm text-slate-500">per month</p><p className="mt-6 border-t border-slate-800 pt-5 text-sm text-slate-300">{detail}</p></div>}
