"use client";

import React, { useMemo, useState } from "react";
import { AlertTriangle, Crosshair, Flag, Gamepad2, Radar, RotateCcw, Route, Search, Shield, Target, Trophy } from "lucide-react";

type ClassLoadout = { id: number; name: string; tier: string; primary: string; secondary: string; perks: string; lethal: string; tactical: string; equipment: string; streaks: string; role: string; useWhen: string; avoid: string; };
type MapPlan = { map: string; classPick: string; backupClass: string; plan: string; attackPlan: string; defensePlan: string; danger: string; publicTip: string; rule: string; };

const classes: ClassLoadout[] = [
  { id: 1, name: "Main Control", tier: "Default", primary: "Galil + Suppressor", secondary: "Python + Speed Reloader", perks: "Ghost Pro / Hardened Pro / Marathon Pro", lethal: "Semtex", tactical: "Concussion", equipment: "Motion Sensor", streaks: "Spy Plane / Counter Spy Plane / Blackbird", role: "Mid-map control, escort, route stabilization, safe flag pressure.", useWhen: "Use when the match is balanced and you need reliable control without exposing your position.", avoid: "Do not reload in open lanes. This class depends on timing, cover, and disciplined movement." },
  { id: 2, name: "Silent Attack", tier: "Elite", primary: "Commando + Suppressor", secondary: "Python + Speed Reloader", perks: "Ghost Pro / Sleight of Hand Pro / Ninja Pro", lethal: "Semtex", tactical: "Concussion", equipment: "Jammer", streaks: "Spy Plane / Counter Spy Plane / Blackbird", role: "Silent flanks, flag-room clearing, building entry, stealth route pressure.", useWhen: "Use when enemies are sound-focused, camping lanes, or over-reading radar pressure.", avoid: "Do not sprint into rooms. Clear one angle, reset, then move." },
  { id: 3, name: "Aggressive Flag Runner", tier: "Must-Have", primary: "AK74u + Suppressor", secondary: "Python + Speed Reloader", perks: "Ghost Pro / Sleight of Hand Pro / Marathon Pro", lethal: "Semtex", tactical: "Concussion", equipment: "Jammer", streaks: "Spy Plane / Counter Spy Plane / Blackbird", role: "Fast flag pressure, close-medium engagements, emergency objective breaks.", useWhen: "Use when your team needs momentum, faster flag pulls, or stronger close-medium objective movement.", avoid: "Do not challenge long rifle lanes unless you already own the angle." },
  { id: 4, name: "Fast Rifle Pressure", tier: "Pressure", primary: "FAMAS + Suppressor", secondary: "Python Speed Reloader or Makarov Extended Mag", perks: "Ghost Pro / Sleight of Hand Pro / Marathon Pro", lethal: "Semtex", tactical: "Concussion", equipment: "Motion Sensor", streaks: "Spy Plane / Counter Spy Plane / Blackbird", role: "High-rate rifle pressure, mid-lane breaks, fast support around the objective.", useWhen: "Use when you need speed and high-rate pressure while keeping rifle-level control.", avoid: "Do not waste shots across extreme distance. Hold pressure inside the weapon's useful lane." },
  { id: 5, name: "Precision Defense", tier: "Surgical", primary: "FN FAL + Red Dot", secondary: "Python + Speed Reloader", perks: "Ghost Pro / Sleight of Hand Pro / Ninja Pro", lethal: "Claymore or Semtex", tactical: "Concussion", equipment: "Motion Sensor", streaks: "Spy Plane / Counter Spy Plane / Blackbird", role: "Long-lane defense, flag-carrier shutdown, quiet defensive positioning.", useWhen: "Use when enemies repeat crossing lanes, long routes, or predictable flag paths.", avoid: "Do not panic-fire. This class rewards first-shot discipline and patience." },
  { id: 6, name: "Anti-Explosive Objective", tier: "Problem Solver", primary: "Galil or Commando + Suppressor", secondary: "Strela-3", perks: "Flak Jacket Pro / Sleight of Hand Pro / Tactical Mask Pro", lethal: "Semtex", tactical: "Concussion", equipment: "Jammer or Claymore", streaks: "Spy Plane / Counter Spy Plane / Blackbird", role: "Objective survival, grenade-heavy matches, stun resistance, air-support denial.", useWhen: "Use when explosives, stuns, equipment, or air support are deciding the match.", avoid: "Without Ghost, Spy Plane can expose you. Move through cover and rotate with purpose." },
];

const maps: MapPlan[] = [
  { map: "Nuketown", classPick: "AK74u + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Marathon Pro / Semtex / Concussion / Jammer / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Flak Jacket Pro / Sleight of Hand Pro / Tactical Mask Pro with Galil or Commando + Suppressor when grenades and stuns control the objective.", plan: "Control one house, mid-car pressure, and enemy crossing lanes. Nuketown is not only about speed; it is about preventing random chaos from becoming your decision system.", attackPlan: "Attack through side-house pressure. Clear window, doorway, staircase, and backyard before touching the flag. Pull only after enemy pressure drops, two enemies are down, or Blackbird opens the route. The carrier leaves through the least watched side while escort cuts the middle chase route.", defensePlan: "Do not sit directly on the flag. Hold the house angle, backyard cutoff, and mid-car pressure. If teammates die on one side, immediately pre-aim that chase lane. Rotate after one or two kills to avoid revenge grenade timing.", danger: "Grenades, window pre-aims, car explosions, backyard spawn flips, panic sprinting through center.", publicTip: "Most public players lose Nuketown CTF by overextending. Let the enemy spawn stay readable unless your team is already pulling the flag.", rule: "Never overextend into the backyard unless your team is actively pulling or returning the flag." },
  { map: "Firing Range", classPick: "Galil + Suppressor / Python + Speed Reloader / Ghost Pro / Hardened Pro / Marathon Pro / Semtex / Concussion / Motion Sensor / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "FN FAL + Red Dot / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro for long-lane defense.", plan: "Control trailer, tower side, and middle cutoffs. The team that denies free mid-map movement usually controls the flag rhythm.", attackPlan: "Use trailer-side or wood-side routes depending on enemy pressure. Stun before entering the flag zone. Clear tower, trailer corner, and middle headglitch before the pull. The flag carrier should not exit alone; escort must cut the side-lane chase.", defensePlan: "Defend from tower sightline, trailer approach, and middle lane rather than standing on the flag. Motion Sensor helps read flank pressure. If enemies repeatedly cross the same angle, switch to FAL and punish the lane.", danger: "Tower, trailer corner, middle headglitches, wood-stack angles, rushed center pulls.", publicTip: "Firing Range rewards escort discipline more than solo hero runs. One puller, one escort, one lane cutter is the clean structure.", rule: "Do not solo-run the flag. Escort and chase-lane denial are mandatory." },
  { map: "Summit", classPick: "Commando + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro / Semtex / Concussion / Jammer / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "AK74u + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Marathon Pro for faster outside pressure.", plan: "Win control room and catwalk timing. Summit is about route selection, sound discipline, and fast changes when a lane is locked.", attackPlan: "If the bridge is locked, stop forcing it and rotate outside snow. If control room is yours, push interior, clear corners, and pull after defenders are displaced. Use Jammer near the enemy flag area to cut their information.", defensePlan: "Hold control room edge, catwalk cutoff, and outside snow rotation. Ninja Pro is valuable because sound reveals route pressure. Rotate after one or two kills; Summit revenge routes are fast.", danger: "Bridge, catwalk, control room corners, lower snow path, predictable bridge challenges.", publicTip: "Most players keep feeding bridge. Professional Summit play means changing the route before the enemy farms it.", rule: "Stop forcing bridge when the enemy owns it. Rotate outside and make them turn around." },
  { map: "Jungle", classPick: "FN FAL + Red Dot / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro / Claymore or Semtex / Concussion / Motion Sensor / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Galil + Suppressor / Python + Speed Reloader / Ghost Pro / Hardened Pro / Marathon Pro for mobile escort and mid-map control.", plan: "Play patient long-lane control. Jungle rewards rifle discipline, early lane reads, and calm movement more than reckless speed.", attackPlan: "Use river and side paths instead of forcing exposed center. Clear cliff, hut lane, and bridge pressure before crossing. Short-range classes must stay on flank routes instead of challenging long rifle angles.", defensePlan: "Lock hut lanes, bridge view, and flag-carrier return routes. FAL is ideal for first-shot defense. Keep cover nearby and avoid tunnel vision on one sightline.", danger: "Cliff, bridge, hut lanes, deep jungle sightlines, exposed crossings.", publicTip: "Jungle punishes sprinting. A slower player with lane discipline beats a faster player exposing full body across long angles.", rule: "Do not challenge long rifle lanes with weak range. Route around them." },
  { map: "Havana", classPick: "Galil + Suppressor / Python + Speed Reloader / Ghost Pro / Hardened Pro / Marathon Pro / Semtex / Concussion / Motion Sensor / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Commando + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro for quiet building-to-building attacks.", plan: "Control buildings and street crossings. Havana punishes careless sprinting and rewards players who clear windows before crossing.", attackPlan: "Move building-to-building. Check both windows before crossing long street. Use concussion before entering flag-side buildings and pull only after the route is clear or enemy attention is forced elsewhere.", defensePlan: "Hold window lines, street cutoff, and interior approaches. Rotate between building angles so enemies cannot pre-aim the same spot. Use FAL when enemies repeat long street paths.", danger: "Long street, upper windows, dark corners, building campers, open crossings.", publicTip: "Public players often die because they cross first and check later. On Havana, checking first is the win condition.", rule: "Never cross open street without checking both windows and long-lane pressure first." },
  { map: "Grid", classPick: "FN FAL + Red Dot / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro / Claymore or Semtex / Concussion / Motion Sensor / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Galil + Suppressor / Python + Speed Reloader / Ghost Pro / Hardened Pro / Marathon Pro for safer mobile control.", plan: "Slow outer control and long-lane shutdown. Grid is a precision map where first-shot accuracy decides most engagements.", attackPlan: "Advance through outer routes with pre-aimed movement. Do not rush server-room corners without clearing both entry points. Pull only when the long-lane defender is removed or distracted.", defensePlan: "Hold long lanes and back-spawn angles. Rotate between the long sightline and flag cutoff after each engagement. Motion Sensor is useful for detecting flank pressure before it reaches the flag.", danger: "Long lanes, server room, back-spawn angles, corner traps, over-sprinting.", publicTip: "Grid rewards the player who slows down first. If you are always sprinting, you are feeding the long-lane player.", rule: "First shot, cover, rotate. Do not play Grid like Nuketown." },
  { map: "WMD", classPick: "Commando + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro / Semtex / Concussion / Jammer / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Galil + Suppressor / Python + Speed Reloader / Ghost Pro / Hardened Pro / Marathon Pro for lane control and escort.", plan: "Clear one section at a time. WMD has too many vertical and horizontal angles for blind sprinting.", attackPlan: "Choose snow route or building route based on enemy pressure. Clear upper windows before crossing. Use Jammer near flag buildings to disrupt information and equipment reliance.", defensePlan: "Control vertical positions, factory lanes, and snow-side movement. Do not chase too deep into enemy territory unless your team is pulling. Prioritize section denial over random kills.", danger: "Upper windows, factory lanes, snow route, hidden corners, multi-angle crossings.", publicTip: "WMD punishes players who try to clear the whole map in one move. Clear one section, reset, then advance.", rule: "Section control first, flag pull second." },
  { map: "Launch", classPick: "FAMAS + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Marathon Pro / Semtex / Concussion / Motion Sensor / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Flak Jacket Pro / Sleight of Hand Pro / Tactical Mask Pro with Galil or Commando + Suppressor if explosives dominate center.", plan: "Control rocket-side timing without standing exposed. Launch rewards speed, but open-center fighting must stay brief.", attackPlan: "Use side route around rocket lane. Stun before crossing and pull after enemy numbers drop. If the center is locked, rotate around instead of challenging the same open angle repeatedly.", defensePlan: "Hold rocket-side cutoff and flag approach angles. If grenades or stuns decide the fight, switch to the anti-explosive class immediately. Rotate after kills to avoid predictable revenge routes.", danger: "Open center, grenade spam, rocket lanes, spawn traps, exposed reloads.", publicTip: "Launch looks like a speed map, but the best players treat the open center like a temporary crossing, not a home.", rule: "Do not stay in open center. Kill, move, reset." },
  { map: "Radiation", classPick: "AK74u + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Marathon Pro / Semtex / Concussion / Jammer / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Commando + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro for quiet underground and building clears.", plan: "Control top-to-underground transitions. Radiation is won by rotation timing, not by repeating one route.", attackPlan: "Use underground if top control is locked, but pre-aim every corner. Use top route only after team pressure creates space. Jammer helps during flag-area entry.", defensePlan: "Hold transition points, not only the flag. If teammates die underground, immediately expect pressure from that route. Rotate between top windows and underground cutoff.", danger: "Underground corners, middle drop, top windows, transition ambushes, blind entries.", publicTip: "The underground route is powerful only when cleared. Entering casually is a free death in Hardcore.", rule: "Never enter underground without pre-aiming every corner." },
  { map: "Array", classPick: "FN FAL + Red Dot / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro / Claymore or Semtex / Concussion / Motion Sensor / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Galil + Suppressor / Python + Speed Reloader / Ghost Pro / Hardened Pro / Marathon Pro for controlled escort across safer routes.", plan: "Long-range discipline map. Array is not a reckless flag-running map; it requires route preparation, escort, and lane denial.", attackPlan: "Use slow outer cover routes and avoid open snowfield sprinting. Pull only with full escort and after tower/satellite pressure is cleared or distracted.", defensePlan: "Hold tower pressure, satellite lanes, and open-field crossings. Use FAL to stop carriers before they reach cover. Do not abandon defense to chase kills across the map.", danger: "Tower, open snow, satellite area, defensive rifles, impossible solo crossings.", publicTip: "Array exposes bad objective discipline. The correct pull is slow, escorted, and prepared before flag contact.", rule: "No solo flag runs across open ground. Escort is mandatory." },
  { map: "Cracked", classPick: "Galil + Suppressor / Python + Speed Reloader / Ghost Pro / Hardened Pro / Marathon Pro / Semtex / Concussion / Motion Sensor / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Commando + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro for building clears and flank pressure.", plan: "Control broken buildings and long middle lanes. Cracked rewards players who rotate after early picks instead of camping one room.", attackPlan: "Use side-building routes and clear upper windows before crossing rubble. Avoid direct center unless Blackbird is active or enemy numbers are down.", defensePlan: "Hold upper windows briefly, then rotate. Watch rubble corners and long street angles. Motion Sensor helps identify slow flanks before they reach flag contact.", danger: "Upper windows, rubble corners, long streets, hidden interiors, predictable building camping.", publicTip: "Cracked is full of strong positions, but staying in one too long gives the enemy a free read.", rule: "Never stay in one building too long. Predictability gets punished." },
  { map: "Crisis", classPick: "Commando + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro / Semtex / Concussion / Jammer / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "AK74u + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Marathon Pro for faster close-route pressure.", plan: "Control beach-side and building routes without chasing too deep. Crisis has multiple flank lanes that can break flag awareness quickly.", attackPlan: "Use beach when mid is watched. Use building route when enemies overextend. Clear hut corners and mid ambush positions before the pull.", defensePlan: "Hold beach long angle and building-route cutoffs. If teammates die near mid, rotate immediately and prepare for a split attack.", danger: "Beach lanes, hut corners, mid ambushes, deep chase traps, split pressure.", publicTip: "Crisis tempts players into chasing. The better player knows when a kill is not worth losing flag control.", rule: "Do not chase kills deep into enemy side if it breaks flag awareness." },
  { map: "Villa", classPick: "Commando + Suppressor / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro / Semtex / Concussion / Jammer / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "FN FAL + Red Dot / Python + Speed Reloader / Ghost Pro / Sleight of Hand Pro / Ninja Pro for balcony and courtyard shutdown.", plan: "Use quiet room clearing and building control. Villa heavily rewards Ninja Pro, patience, and controlled interior movement.", attackPlan: "Move through side building, clear rooms slowly, and pull only after defenders are removed or displaced. Do not sprint into courtyards without checking balconies.", defensePlan: "Hold balcony pressure, courtyard cutoffs, and interior entrances. Stop attackers before flag contact instead of sitting on the flag and reacting late.", danger: "Balconies, courtyard crossings, interior corners, sound-based campers, blind room entry.", publicTip: "Villa is where quiet movement creates free kills. Ninja Pro is a strategic advantage, not just a comfort perk.", rule: "Quiet movement wins routes before gunfights start." },
  { map: "Hanoi", classPick: "Galil + Suppressor / Python + Speed Reloader / Ghost Pro / Hardened Pro / Marathon Pro / Semtex / Concussion / Motion Sensor / Spy Plane + Counter Spy Plane + Blackbird", backupClass: "Flak Jacket Pro / Sleight of Hand Pro / Tactical Mask Pro with Galil or Commando + Suppressor if grenades and stuns dominate rooms.", plan: "Slow doorway clears and side-route pressure. Visibility and corner discipline matter heavily on Hanoi.", attackPlan: "Approach through covered side lanes. Stun before room entry and avoid blind sprinting through dark interiors. Pull only after upper pressure and doorway angles are controlled.", defensePlan: "Hold upper levels, prison lanes, and flag-side approaches. Rotate after kills and use Motion Sensor to detect slow room-to-room pressure.", danger: "Dark corners, upper levels, prison lanes, explosive spam, blind door entry.", publicTip: "Hanoi punishes players who rush rooms without checking corners. Slow entry is not passive; it is professional survival.", rule: "Slow down before every doorway. Hardcore Hanoi punishes blind entry." },
];

const principles = [
  { icon: Flag, title: "Flag Timing", text: "Pull only when the route is cleared, two enemies are down, or your escort is ready." },
  { icon: Radar, title: "Information Chain", text: "Spy Plane, Counter Spy Plane, and Blackbird create clean pulls and safer escorts." },
  { icon: Route, title: "Route Discipline", text: "If you die twice on one route, immediately rotate to a different lane." },
  { icon: Shield, title: "Survival Switch", text: "Swap to Flak Jacket/Tactical Mask when explosives and stuns decide the match." },
  { icon: Crosshair, title: "First-Shot Rule", text: "Hardcore rewards pre-aim, half-second patience, and cover before ego challenges." },
  { icon: RotateCcw, title: "Kill, Move, Reset", text: "After 1-2 kills, rotate before the enemy reads your position." },
];
const drills = ["10 minutes: single-shot accuracy and first-bullet control.", "10 minutes: pre-aim every common corner on two maps.", "5 matches: count deaths while sprinting into danger zones.", "5 matches: run objective routes only, no useless kill chasing.", "Post-match: log the top reason you died and fix only that next match."];

export default function BlackOpsHardcoreCTFSystem() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All");
  const [selectedClass, setSelectedClass] = useState<ClassLoadout>(classes[0]);
  const [selectedMap, setSelectedMap] = useState<MapPlan>(maps[0]);
  const filteredClasses = useMemo(() => classes.filter((item) => (filter === "All" || item.name.includes(filter) || item.tier.includes(filter)) && `${item.name} ${item.primary} ${item.perks} ${item.role}`.toLowerCase().includes(query.toLowerCase())), [query, filter]);

  return (
    <section className="min-h-screen bg-[#0B1220] text-slate-100 p-4 md:p-8">
      <div className="mx-auto max-w-7xl space-y-6">
        <div className="grid gap-4 lg:grid-cols-[1.5fr_.8fr]">
          <Panel><div className="flex items-center gap-3 mb-4"><div className="p-3 rounded-2xl bg-cyan-400/15"><Trophy className="text-cyan-300" /></div><div><h1 className="text-3xl md:text-4xl font-bold tracking-tight text-white">Black Ops 1 Hardcore CTF Success Dashboard</h1><p className="text-slate-300 mt-1">Professional loadouts, map strategy, decision rules, and training discipline for public use.</p></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6"><Stat label="Mode" value="Hardcore CTF" /><Stat label="Primary Goal" value="Win Flags" /><Stat label="Streak Chain" value="UAV / CUAV / Blackbird" /><Stat label="Core Rule" value="Map Control First" /></div></Panel>
          <Panel><h2 className="text-xl font-semibold mb-3 flex gap-2 items-center text-white"><AlertTriangle className="text-amber-300" /> Match Priority</h2><div className="space-y-3 text-sm text-slate-200"><Priority n="1" text="Control map lanes before chasing kills." /><Priority n="2" text="Pull flag only after timing window opens." /><Priority n="3" text="Escort by cutting enemy chase routes." /><Priority n="4" text="Switch classes before the match collapses." /></div></Panel>
        </div>
        <div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
          <Panel><div className="flex flex-col md:flex-row gap-3 md:items-center md:justify-between mb-4"><h2 className="text-2xl font-bold flex items-center gap-2 text-white"><Gamepad2 className="text-cyan-300" /> Six-Class Arsenal</h2><div className="flex flex-wrap gap-2">{["All", "Elite", "Must-Have", "Problem Solver"].map((x) => <button key={x} onClick={() => setFilter(x)} className={`rounded-xl px-4 py-2 text-sm font-medium transition ${filter === x ? "bg-cyan-500 text-slate-950 hover:bg-cyan-400" : "bg-[#1A2942] text-slate-100 hover:bg-[#223653] border border-[#334768]"}`}>{x}</button>)}</div></div><div className="relative mb-4"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search weapon, perk, role..." className="w-full bg-[#0B1220] border border-[#334768] rounded-2xl py-2.5 pl-10 pr-3 text-sm text-white placeholder:text-slate-500 outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/20" /></div><div className="grid gap-3">{filteredClasses.map((item) => <button key={item.id} onClick={() => setSelectedClass(item)} className={`text-left p-4 rounded-2xl border transition ${selectedClass.id === item.id ? "border-cyan-400 bg-cyan-400/10 shadow-sm" : "border-[#263550] bg-[#0F1A2B] hover:bg-[#17263E]"}`}><div className="flex justify-between gap-3"><div><p className="font-semibold text-white">{item.id}. {item.name}</p><p className="text-sm text-slate-300">{item.primary}</p></div><span className="text-xs px-2 py-1 rounded-full bg-[#1A2942] text-cyan-200 h-fit border border-[#334768]">{item.tier}</span></div></button>)}</div></Panel>
          <Panel><h2 className="text-2xl font-bold mb-1 flex items-center gap-2 text-white"><Target className="text-emerald-300" /> {selectedClass.name}</h2><p className="text-slate-300 mb-5">{selectedClass.role}</p><div className="grid md:grid-cols-2 gap-3 text-sm"><Info label="Primary" value={selectedClass.primary} /><Info label="Secondary" value={selectedClass.secondary} /><Info label="Perks" value={selectedClass.perks} /><Info label="Lethal" value={selectedClass.lethal} /><Info label="Tactical" value={selectedClass.tactical} /><Info label="Equipment" value={selectedClass.equipment} /><Info label="Killstreaks" value={selectedClass.streaks} wide /><Info label="Use When" value={selectedClass.useWhen} wide /><Info label="Avoid" value={selectedClass.avoid} wide warning /></div></Panel>
        </div>
        <div className="grid gap-6 lg:grid-cols-[1fr_.85fr]">
          <Panel><h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-white"><Route className="text-indigo-300" /> Professional Map Strategy Matrix</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mb-5">{maps.map((m) => <button key={m.map} onClick={() => setSelectedMap(m)} className={`p-3 rounded-2xl text-left border transition ${selectedMap.map === m.map ? "bg-indigo-400/10 border-indigo-300 shadow-sm" : "bg-[#0F1A2B] border-[#263550] hover:bg-[#17263E]"}`}><p className="font-semibold text-white">{m.map}</p><p className="text-xs text-slate-300 line-clamp-2">{m.classPick}</p></button>)}</div><div className="rounded-2xl border border-[#263550] bg-[#0F1A2B] p-5"><h3 className="text-xl font-bold mb-3 text-white">{selectedMap.map}</h3><div className="grid md:grid-cols-2 gap-3 text-sm"><Info label="Complete Best Class Pick" value={selectedMap.classPick} wide /><Info label="Backup / Adjustment Class" value={selectedMap.backupClass} wide /><Info label="Primary Plan" value={selectedMap.plan} wide /><Info label="Attack Route Plan" value={selectedMap.attackPlan} wide /><Info label="Defense / Escort Plan" value={selectedMap.defensePlan} wide /><Info label="Danger Lanes" value={selectedMap.danger} warning /><Info label="Public Player Tip" value={selectedMap.publicTip} /><Info label="Map Rule" value={selectedMap.rule} warning /></div></div></Panel>
          <Panel><h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-white"><Crosshair className="text-rose-300" /> Player Upgrade System</h2><div className="grid gap-3 mb-5">{principles.map(({ icon: Icon, title, text }) => <div key={title} className="p-4 rounded-2xl bg-[#0F1A2B] border border-[#263550]"><div className="flex gap-3"><Icon className="text-cyan-300 shrink-0" /><div><p className="font-semibold text-white">{title}</p><p className="text-sm text-slate-300">{text}</p></div></div></div>)}</div><div className="p-4 rounded-2xl bg-emerald-400/10 border border-emerald-300/30"><h3 className="font-bold text-emerald-200 mb-2">Daily Training Loop</h3><ol className="list-decimal list-inside text-sm text-slate-200 space-y-1">{drills.map((d) => <li key={d}>{d}</li>)}</ol></div></Panel>
        </div>
        <footer className="rounded-2xl border border-[#263550] bg-[#111C2E] p-5 md:p-6 shadow-xl shadow-black/30"><div className="space-y-4"><div><p className="text-xs uppercase tracking-wide text-cyan-200 mb-2">Public Use Disclaimer</p><p className="text-sm leading-relaxed text-slate-300">Disclaimer: This informational system is an independent, fan-made strategy resource for Call of Duty: Black Ops 1 Hardcore Capture the Flag gameplay. It is not affiliated with, endorsed by, sponsored by, or officially connected to Activision, Treyarch, or Call of Duty. All game names, map names, weapon names, perk names, and related trademarks belong to their respective owners. The strategies provided are for educational and gameplay-improvement purposes only and do not guarantee specific performance, rankings, wins, or professional results.</p></div><div className="rounded-2xl border border-cyan-300/20 bg-cyan-400/10 p-4"><p className="text-xs uppercase tracking-wide text-cyan-200 mb-2">Short Notice</p><p className="text-sm leading-relaxed text-slate-200">Independent fan-made strategy resource. Not affiliated with Activision, Treyarch, or Call of Duty. All trademarks belong to their respective owners. Information is for gameplay education only and does not guarantee results.</p></div></div></footer>
      </div>
    </section>
  );
}
function Panel({ children }: { children: React.ReactNode }) { return <div className="bg-[#111C2E] border border-[#263550] rounded-2xl shadow-xl shadow-black/30 p-5 md:p-6">{children}</div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-[#263550] bg-[#0F1A2B] p-4"><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="font-bold text-white mt-1">{value}</p></div>; }
function Priority({ n, text }: { n: string; text: string }) { return <div className="flex gap-3 items-start"><span className="h-7 w-7 rounded-full bg-cyan-400/15 flex items-center justify-center text-xs font-bold text-cyan-200">{n}</span><p className="text-slate-200">{text}</p></div>; }
function Info({ label, value, wide, warning }: { label: string; value: string; wide?: boolean; warning?: boolean }) { return <div className={`${wide ? "md:col-span-2" : ""} rounded-2xl border ${warning ? "border-amber-300/30 bg-amber-400/10" : "border-[#263550] bg-[#0F1A2B]"} p-4`}><p className="text-xs uppercase tracking-wide text-slate-400 mb-1">{label}</p><p className="text-slate-100 leading-relaxed">{value}</p></div>; }
