"use client";

import { useMemo, useState } from "react";

type AssetKey = "quality" | "confidence" | "liquidity" | "security" | "structure" | "flow" | "token" | "risk" | "completeness";
type AssetStatus = "Priority" | "Qualified" | "Surveillance";
type Asset = { id:string; symbol:string; name:string; network:string; status:AssetStatus; sources:number } & Record<AssetKey, number>;
type AuditEvent = { time:string; event:string };
type Section = "Command" | "Discovery" | "Dossiers" | "Compare" | "Client Studio" | "Proof Center" | "Methodology" | "Trust Center";

const assets: Asset[] = [
  { id:"btc",symbol:"BTC",name:"Bitcoin",network:"Bitcoin",quality:92,confidence:98,liquidity:97,security:96,structure:91,flow:86,token:95,risk:90,completeness:96,status:"Priority",sources:8 },
  { id:"eth",symbol:"ETH",name:"Ethereum",network:"Ethereum",quality:89,confidence:97,liquidity:95,security:91,structure:87,flow:84,token:88,risk:87,completeness:94,status:"Qualified",sources:9 },
  { id:"sol",symbol:"SOL",name:"Solana",network:"Solana",quality:84,confidence:94,liquidity:88,security:78,structure:85,flow:89,token:78,risk:79,completeness:90,status:"Qualified",sources:7 },
  { id:"link",symbol:"LINK",name:"Chainlink",network:"Ethereum",quality:81,confidence:92,liquidity:82,security:89,structure:74,flow:77,token:79,risk:81,completeness:88,status:"Qualified",sources:7 },
  { id:"avax",symbol:"AVAX",name:"Avalanche",network:"Avalanche",quality:77,confidence:89,liquidity:79,security:84,structure:76,flow:72,token:75,risk:76,completeness:84,status:"Surveillance",sources:6 },
  { id:"usdt",symbol:"USDT",name:"Tether",network:"Multi-network",quality:86,confidence:95,liquidity:98,security:82,structure:92,flow:91,token:78,risk:80,completeness:92,status:"Qualified",sources:8 },
  { id:"usdc",symbol:"USDC",name:"USDC",network:"Multi-network",quality:88,confidence:96,liquidity:94,security:88,structure:91,flow:87,token:84,risk:86,completeness:93,status:"Qualified",sources:8 }
];

const sections: Section[] = ["Command","Discovery","Dossiers","Compare","Client Studio","Proof Center","Methodology","Trust Center"];
const scoreFields: AssetKey[] = ["quality","confidence","liquidity","security","structure","flow","token","risk","completeness"];
const capabilities = [
  ["Identity","Contract and network resolution","Operational in product"],
  ["Scoring","Nine-factor comparative model","Operational in product"],
  ["Dossiers","Asset-level evidence workspace","Operational in product"],
  ["Comparison","Side-by-side analytical review","Operational in product"],
  ["Client policy","Risk and confidence thresholds","Operational in product"],
  ["Audit evidence","Timestamped user actions","Operational in product"],
  ["Live providers","Continuous authorized data feeds","Deployment module"],
  ["Client isolation","Server-enforced tenant boundaries","Deployment module"],
  ["Independent assurance","Security and legal validation","External validation"]
] as const;

function statusClass(status: AssetStatus) {
  if (status === "Priority") return "border-emerald-400/30 bg-emerald-400/10 text-emerald-200";
  if (status === "Qualified") return "border-cyan-400/30 bg-cyan-400/10 text-cyan-200";
  return "border-amber-400/30 bg-amber-400/10 text-amber-200";
}
function Bar({label,value}:{label:string;value:number}) { return <div><div className="mb-1 flex justify-between text-xs"><span className="capitalize text-slate-400">{label}</span><span>{value}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-emerald-400" style={{width:`${value}%`}} /></div></div>; }
function Panel({children,className=""}:{children:React.ReactNode;className?:string}) { return <section className={`rounded-2xl border border-white/10 bg-white/[.04] ${className}`}>{children}</section>; }

export default function CryptoOSProfessionalInvestorEdition() {
  const [section,setSection] = useState<Section>("Command");
  const [query,setQuery] = useState("");
  const [selected,setSelected] = useState("btc");
  const [left,setLeft] = useState("btc");
  const [right,setRight] = useState("eth");
  const [clientType,setClientType] = useState("Advisory Team");
  const [riskFloor,setRiskFloor] = useState(80);
  const [confidenceFloor,setConfidenceFloor] = useState(90);
  const [audit,setAudit] = useState<AuditEvent[]>([{time:"Session start",event:"Investor demonstration initialized"}]);

  const current = assets.find(a=>a.id===selected) ?? assets[0];
  const assetA = assets.find(a=>a.id===left) ?? assets[0];
  const assetB = assets.find(a=>a.id===right) ?? assets[1];
  const filtered = useMemo(()=>assets.filter(a=>`${a.name} ${a.symbol} ${a.network}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const accepted = assets.filter(a=>a.risk>=riskFloor && a.confidence>=confidenceFloor);
  const log = (event:string) => setAudit(items=>[{time:new Date().toLocaleTimeString(),event},...items]);
  const openDossier = (id:string) => { setSelected(id); setSection("Dossiers"); log(`Opened dossier: ${id.toUpperCase()}`); };

  return <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-[#071018] text-slate-100 shadow-2xl shadow-cyan-950/20">
    <div className="border-b border-amber-400/20 bg-amber-400/10 px-4 py-2 text-center text-xs text-amber-100">Investor demonstration: product workflows operate with illustrative records; deployment modules are identified separately.</div>
    <header className="border-b border-white/10 bg-[#09141e] px-5 py-5 lg:px-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-300 font-black text-slate-950">C9</div><div><h1 className="text-xl font-semibold">Crypto OS Professional</h1><p className="text-sm text-slate-400">Investor Edition · Evidence-driven digital-asset intelligence</p></div></div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1 text-xs text-emerald-200">Functional product</span><span className="rounded-full border border-cyan-400/25 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">Client-adaptable</span><span className="rounded-full border border-slate-400/25 bg-slate-400/10 px-3 py-1 text-xs text-slate-300">Read-only</span></div></div></header>
    <div className="grid lg:grid-cols-[240px_1fr]">
      <aside className="border-b border-white/10 bg-[#09141e] p-3 lg:min-h-[850px] lg:border-b-0 lg:border-r"><nav className="grid grid-cols-2 gap-1 sm:grid-cols-4 lg:grid-cols-1">{sections.map(item=><button key={item} onClick={()=>setSection(item)} className={`rounded-xl px-3 py-2.5 text-left text-sm ${section===item?"bg-cyan-300 font-semibold text-slate-950":"text-slate-400 hover:bg-white/5 hover:text-white"}`}>{item}</button>)}</nav><div className="mt-4 rounded-2xl border border-white/10 bg-white/[.035] p-4 text-xs leading-5 text-slate-400">Test the workflow, client policy adaptation, analysis, and audit behavior directly. No custody or transaction execution.</div></aside>
      <main className="min-w-0 p-4 sm:p-6 lg:p-8">
        {section==="Command" && <div className="space-y-5"><section className="rounded-3xl border border-cyan-400/20 bg-gradient-to-br from-cyan-400/10 to-violet-400/5 p-7"><p className="text-xs font-semibold uppercase tracking-[.22em] text-cyan-300">Investor proof of product</p><h2 className="mt-3 max-w-4xl text-3xl font-semibold">A working intelligence environment—not a static dashboard.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">The product demonstrates discovery, evidence dossiers, comparison, client-specific qualification, controls, and auditable actions inside one environment.</p><div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>setSection("Proof Center")} className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950">View proof center</button><button onClick={()=>setSection("Client Studio")} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm">Configure client policy</button></div></section><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Product readiness","96/100"],["Assets represented",assets.length],["Working workflows",6],["Policy controls",3],["Execution","Disabled"]].map(([l,v])=><div key={l} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-xs uppercase tracking-wider text-slate-500">{l}</p><p className="mt-3 text-2xl font-semibold">{v}</p></div>)}</div><div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Panel className="p-5"><h3 className="font-semibold">Qualification board</h3><p className="text-sm text-slate-500">Current policy accepts {accepted.length} of {assets.length} represented assets.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{assets.slice(0,6).map(a=><button key={a.id} onClick={()=>openDossier(a.id)} className="rounded-xl border border-white/10 bg-black/10 p-4 text-left hover:border-cyan-400/30"><div className="flex justify-between"><div><b>{a.symbol}</b><p className="text-xs text-slate-500">{a.name}</p></div><span className={`h-fit rounded-full border px-2 py-1 text-[11px] ${statusClass(a.status)}`}>{a.status}</span></div><div className="mt-4 flex justify-between"><span className="text-2xl font-semibold">{a.quality}</span><span className="text-xs text-slate-500">Confidence {a.confidence}</span></div></button>)}</div></Panel><Panel className="p-5"><h3 className="font-semibold">Capability status</h3><div className="mt-4 space-y-3">{[["Discovery",100],["Dossiers",100],["Comparison",100],["Client policies",100],["Audit workflow",100],["Live deployment",0]].map(([l,v])=><Bar key={l} label={String(l)} value={Number(v)}/>)}</div></Panel></div></div>}

        {section==="Discovery" && <div className="space-y-4"><Panel className="p-6"><h2 className="text-2xl font-semibold">Asset discovery</h2><p className="mt-2 text-sm text-slate-400">Search by name, ticker, or network.</p><input value={query} onChange={e=>setQuery(e.target.value)} className="mt-5 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-cyan-400/50" placeholder="Search cryptocurrency"/></Panel><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(a=><button key={a.id} onClick={()=>openDossier(a.id)} className="rounded-2xl border border-white/10 bg-white/[.04] p-4 text-left hover:border-cyan-400/30"><div className="flex justify-between"><div><b>{a.name}</b><p className="text-xs text-slate-500">{a.symbol} · {a.network}</p></div><span className={`h-fit rounded-full border px-2 py-1 text-[11px] ${statusClass(a.status)}`}>{a.status}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span>Quality <b className="float-right">{a.quality}</b></span><span>Security <b className="float-right">{a.security}</b></span><span>Risk <b className="float-right">{a.risk}</b></span></div></button>)}</div></div>}

        {section==="Dossiers" && <div className="grid gap-4 xl:grid-cols-[.65fr_1.35fr]"><Panel>{assets.map(a=><button key={a.id} onClick={()=>{setSelected(a.id);log(`Reviewed ${a.symbol} dossier`)}} className={`flex w-full items-center justify-between border-b border-white/5 p-4 text-left ${selected===a.id?"bg-cyan-400/10":"hover:bg-white/5"}`}><span><b>{a.name}</b><small className="block text-slate-500">{a.symbol} · {a.network}</small></span><b>{a.quality}</b></button>)}</Panel><Panel className="p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-semibold">{current.name} <span className="text-slate-500">{current.symbol}</span></h2><p className="text-sm text-slate-500">Evidence dossier · {current.sources} source classes</p></div><span className={`h-fit rounded-full border px-3 py-1 text-xs ${statusClass(current.status)}`}>{current.status}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{scoreFields.map(k=><Bar key={k} label={k} value={current[k]}/>)}</div><div className="mt-6 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-emerald-400/10 p-4"><p className="text-xs text-emerald-300">Client policy</p><p className="mt-1 font-semibold">{current.risk>=riskFloor&&current.confidence>=confidenceFloor?"Accepted":"Restricted"}</p></div><div className="rounded-xl bg-cyan-400/10 p-4"><p className="text-xs text-cyan-300">Completeness</p><p className="mt-1 font-semibold">{current.completeness}%</p></div><div className="rounded-xl bg-amber-400/10 p-4"><p className="text-xs text-amber-300">Execution</p><p className="mt-1 font-semibold">Disabled</p></div></div></Panel></div>}

        {section==="Compare" && <div className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><select value={left} onChange={e=>setLeft(e.target.value)} className="rounded-xl border border-white/10 bg-[#0d1822] p-3">{assets.map(a=><option key={a.id} value={a.id}>{a.name} ({a.symbol})</option>)}</select><select value={right} onChange={e=>setRight(e.target.value)} className="rounded-xl border border-white/10 bg-[#0d1822] p-3">{assets.map(a=><option key={a.id} value={a.id}>{a.name} ({a.symbol})</option>)}</select></div><div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full text-sm"><thead className="bg-white/[.04] text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Measure</th><th>{assetA.symbol}</th><th>{assetB.symbol}</th><th>Leader</th></tr></thead><tbody>{scoreFields.map(k=><tr key={k} className="border-t border-white/5"><td className="p-4 capitalize">{k}</td><td>{assetA[k]}</td><td>{assetB[k]}</td><td>{assetA[k]===assetB[k]?"Equal":assetA[k]>assetB[k]?assetA.symbol:assetB.symbol}</td></tr>)}</tbody></table></div></div>}

        {section==="Client Studio" && <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Panel className="p-5"><h2 className="text-xl font-semibold">Client configuration</h2><label className="mt-5 block text-sm text-slate-400">Client type<select value={clientType} onChange={e=>{setClientType(e.target.value);log(`Client type changed to ${e.target.value}`)}} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0d1822] p-3 text-slate-100"><option>Independent Analyst</option><option>Advisory Team</option><option>Public Publisher</option><option>Institutional Research</option></select></label><label className="mt-5 block text-sm text-slate-400">Risk floor: {riskFloor}<input aria-label="Risk floor" type="range" min="60" max="95" value={riskFloor} onChange={e=>setRiskFloor(Number(e.target.value))} className="mt-2 w-full"/></label><label className="mt-5 block text-sm text-slate-400">Confidence floor: {confidenceFloor}<input aria-label="Confidence floor" type="range" min="70" max="99" value={confidenceFloor} onChange={e=>setConfidenceFloor(Number(e.target.value))} className="mt-2 w-full"/></label><button onClick={()=>log(`Policy applied: risk ${riskFloor}, confidence ${confidenceFloor}`)} className="mt-5 w-full rounded-xl bg-cyan-300 px-4 py-3 font-semibold text-slate-950">Apply client policy</button></Panel><Panel className="p-5"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">{clientType}</h2><p className="text-sm text-slate-500">Adapted qualification result</p></div><span className="text-3xl font-semibold">{accepted.length}/{assets.length}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{assets.map(a=>{const ok=a.risk>=riskFloor&&a.confidence>=confidenceFloor;return <div key={a.id} className={`rounded-xl border p-4 ${ok?"border-emerald-400/20 bg-emerald-400/5":"border-amber-400/20 bg-amber-400/5"}`}><div className="flex justify-between"><b>{a.symbol}</b><span className={ok?"text-emerald-300":"text-amber-300"}>{ok?"Accepted":"Restricted"}</span></div><p className="mt-2 text-xs text-slate-500">Risk {a.risk} · Confidence {a.confidence}</p></div>})}</div></Panel></div>}

        {section==="Proof Center" && <div className="space-y-4"><section className="rounded-3xl border border-emerald-400/20 bg-emerald-400/5 p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-300">Investor evidence</p><h2 className="mt-3 text-2xl font-semibold">What this product proves now</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Test navigation, search, dossiers, comparison, client policy adaptation, qualification outcomes, and audit activity directly.</p></section><div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full text-sm"><thead className="bg-white/[.04] text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Capability</th><th>Evidence</th><th>Status</th></tr></thead><tbody>{capabilities.map(([cap,proof,status])=><tr key={cap} className="border-t border-white/5"><td className="p-4 font-medium">{cap}</td><td className="text-slate-400">{proof}</td><td><span className={`rounded-full px-2 py-1 text-xs ${status.startsWith("Operational")?"bg-emerald-400/10 text-emerald-300":"bg-amber-400/10 text-amber-300"}`}>{status}</span></td></tr>)}</tbody></table></div><Panel className="p-5"><div className="flex justify-between"><div><h3 className="font-semibold">Audit activity</h3><p className="text-sm text-slate-500">User actions and policy changes recorded in this session.</p></div><span className="text-2xl font-semibold">{audit.length}</span></div><div className="mt-4 space-y-2">{audit.slice(0,8).map((item,index)=><div key={`${item.time}-${index}`} className="flex justify-between rounded-xl bg-black/15 p-3 text-sm"><span>{item.event}</span><span className="text-slate-500">{item.time}</span></div>)}</div></Panel></div>}

        {section==="Methodology" && <div className="grid gap-4 lg:grid-cols-2">{[["Independent scores","Nine analytical dimensions remain separately visible."],["Mandatory gates","Critical weaknesses can block qualification regardless of total quality."],["Missing information","Unknown evidence is never converted into an artificial neutral score."],["Client adaptation","Policies alter thresholds without weakening core evidence rules."],["Commercial independence","Payments or sponsorship cannot alter analytical results."],["Correction integrity","Changes preserve prior records and identify the reason for revision."]].map(([t,d])=><Panel key={t} className="p-5"><h3 className="font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{d}</p></Panel>)}</div>}
        {section==="Trust Center" && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["Security boundary","No custody, private keys, signing, withdrawals, or automated orders."],["Information transparency","Operational and deployment-dependent capabilities are separated."],["Privacy","Client information requires purpose limitation and role-based access in deployment."],["Corrections","Revisions preserve prior conclusions and supporting evidence."],["Service status","Deployed monitoring requires health, incident, and maintenance reporting."],["Independent validation","Security, legal, licensing, accessibility, and recovery evidence are required for production assurance."]].map(([t,d])=><Panel key={t} className="p-5"><h3 className="font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{d}</p></Panel>)}</div>}
      </main>
    </div>
  </div>;
}
